#!/usr/bin/env bash
# This script displays listening TCP and UDP ports with their PID and program name

# Active Internet connections (TCP/UDP)
echo "Active Internet connections (only servers)"
sudo netstat -tulpn | tail -n +3  # başlığı çıxarmaq üçün ilk iki sətri atırıq

# Active UNIX domain sockets
echo "Active UNIX domain sockets (only servers)"
sudo netstat -lxpn | tail -n +3
